### ISSUE TITLE
Rename DJANAGO_ALLOWED_HOSTS to DJANGO_ALLOWED_HOST

### ISSUE THREAD

**Issue by ghost** [maxking/docker-mailman#129]
While `SMTP_HOST` and `MAILMAN_HOST_IP` allow specifying where the mailman posterius and the smtp server connect from, `ALLOWED_HOSTS `cannot be configured via an environment option to specify frontend proxy IP. This makes the container unusable in environments with pre-existing subnets where this ip cannot be easily assigned to that container. Therefore, please also make this ALLOWED_HOSTS ip entry configurable.

**Comment by maxking** [comment]
`SERVE_FROM_DOMAIN` will add the given IP address/hostname to `ALLOWED_HOSTS` in Django. See the configuration linked below.

You can also override the variable  in `settings_local.py`.

https://github.com/maxking/docker-mailman/blob/master/web/mailman-web/settings.py#L54

**Comment by maxking** [comment]
I think the variable is poorly named though ;-)

**Comment by JonasT** [comment]
`SERVE_FROM_DOMAIN` appears to be useless for this purpose, because it needs to be set to a valid domain since it's also used here: `"from django.contrib.sites.models import Site; Site.objects.filter(domain='example.com').update(domain='$SERVE_FROM_DOMAIN')"`

You are assuming that the forward proxy is also the externally reachable endpoint with that domain pointing to it. This is not true for all setups, and therefore a separate variable needs to be available for this.

**Comment by maxking** [comment]
Ah! I guess it makes sense to have a variable to be included in ALLOWED_HOSTS which is not SERVE_FROM_DOMAIN.

Thanks for clarifying it. I will add one soon.

**Comment by JonasT** [comment]
Name suggestion: `FORWARD_PROXY_ADDRESS` (which, if not set, could reasonably default to `SERVE_FROM_DOMAIN`)

**Comment by JonasT** [comment]
@maxking maybe it would be a bit clearer for users stumbling across this new var if it was named `DJANGO_ALLOWED_HOST`? (since it's just a single entry rather than a list)

**Comment by maxking** [comment]
Hmmm I think I agree to that point.

Although, technically speaking, you can specify multiple values separated by comma and it should work.
