### ISSUE TITLE
Can't find the option to set where "password forgotten" e-mails will be sent from

### ISSUE THREAD

**Issue by JonasT** [maxking/docker-mailman#132]
I can't find any option for the mailman web container to set where "password forgotten" e-mails will be sent from. They seem to be sent from `postorius@localhost.local` instead of the proper hostname, and I can't find any option to configure it.

Since our e-mail relay hard-rejects anything with not a proper sender domain, we can't use mailman unless we get this fixed..

**Comment by maxking** [comment]
http://docs.mailman3.org/en/latest/config-web.html#setting-up-email-required

`DEFAULT_FROM_EMAIL` is what you are looking for I guess.

**Comment by maxking** [comment]
It has to be configured in the `settings_local.py` though, there is no environment variable to do this.

**Comment by JonasT** [comment]
It would be nice if it could be added. We did work around this with postfix hacks to get it to run, but it'd be nicer if this was properly configurable.

**Comment by maxking** [comment]
This is actually the *proper* way to configure it in Django. It is True that not *all* the options from Django are configurable via Environment Variables in the images, I am not sure how to even make that work.

For simple `var=value` it should not be a problem though, maybe I will add some python snippet to do that.

**Comment by JonasT** [comment]
Well for a start, you could simply set it to `SERV_FROM_DOMAIN` per default. This wouldn't require an additional option and it would be a much more reasonable default guess than `localhost.local`.

I'm not sure if really all mailmanweb django options need to be configurable as long as the defaults are reasonable (and for this particular instance I think the default isn't very good). Maybe mailman itself could also be patched to default to the django domain instead of `localhost.local`? This wouldn't even require work in the docker image itself.

**Comment by maxking** [comment]
The Django settings from Mailman has always been provided as an example for users to build on, or distributions to configure reasonable defaults and provide to users. Although, I have seen that people installing from source (since there are no packages available yet!) use the default configuration, mostly because a lot of them aren't familiar with Django.

Using SERVE_FROM_DOMAIN in the container images is a good idea! Pull Requests are welcome too!

I would have to think about how would this be implemented directly in Mailman, by-default, the domain created by Django is `example.com`, which is no better than `localhost.local`.

**Comment by maxking** [comment]
Fixed with #141
