### ISSUE TITLE
including special characters in API or SECRET keys causes errors

### ISSUE THREAD

**Issue by fsantiago07044** [maxking/docker-mailman#163]
i had hyperkitty api and secret keys defined with special characters. this caused me errors when creating or accessing the properties of new lists.

see attached mailman.log from mailman-core:

[mailman.log](https://github.com/maxking/docker-mailman/files/1415046/mailman.log)

same keys also caused errors when starting the mailman containers:

WARNING: The JQ3K variable is not set. Defaulting to a blank string.
WARNING: The Va0L variable is not set. Defaulting to a blank string.
WARNING: The Mpu variable is not set. Defaulting to a blank string.

do you need anything else from me?

**Comment by maxking** [comment]
I think it happens because we set the environment variable in docker-compose without quotes (" ") around them and so special characters that bash finds to be useful end up screwing things up.

I have seen something like this happening at other places too in applications that I work on. I will need to think a bit more about what can be done about it.

**Comment by fsantiago07044** [comment]
ok very well. thanks.
