### ISSUE TITLE
Digests

### ISSUE THREAD

**Issue by brianemwd** [maxking/docker-mailman#344]
How are the scheduling of digests handled with your Docker/Mailman setup? I did not see any documentation on that. Is it possible to schedule a particular time to send out a summary digest? Is it possible to schedule a particular time to send out a summary digest for a particular list?

Thank you for your time.
Brian

**Comment by maxking** [comment]
Currently periodic digests aren’t supported by images. You can add a cron job on the host that runs a specific command to do that daily.

I don’t remember the command of the top of my head `mailman —help` should give you the right command to run, I think it is `mailman send`. 

You can configure digests to be either periodic or after reaching a specific size. The one with specific size should work since it doesn’t need a routine job.

It should be possible to add scheduler to core’s image to do this, but I am debating if it is worth doing or there are better ways to do it.
