### ISSUE TITLE
ARC Support

### ISSUE THREAD

**Issue by SomeGeek** [maxking/docker-mailman#367]
Support mailman's [ARC](https://mailman.readthedocs.io/en/latest/src/mailman/handlers/docs/arc_sign.html) feature out of the box.

Edit: Originally, I thought it wasn't easy to add custom config to mailman.cfg. Didn't notice there was a special file for that.

**Comment by maxking** [comment]
Yes, it is totally possible to specify a config file that is added to the running Mailman. 

I don't think setting up ARC by default is a good idea, it should be setup in your MTA so that *all* emails going out actually are Signed, not just the ones that Mailman sends out. Mailman only provides it for the folks who don't have an MTA that supports ARC.
