### ISSUE TITLE
Run in parallel with mailcow-dockerized

### ISSUE THREAD

**Issue by strarsis** [maxking/docker-mailman#403]
Is it possible to run docker-mailman in parallel with mailcow-dockerized?
The main issue that comes to mind is the web frontend that has to be passed through by a reverse proxy?

**Comment by monofox** [comment]
@strarsis, yes is possible. 
Some configurations must be done in order to proper connect from mailman-core to postfix and inverse. 

Actually i configured a volume to have access to the regexp lists on postfix container as well as on mailman-core container. Furthermore it was necessary to overwrite the mta configuration in order to force the STARTTLS. 

Also i needed to work with the vmap from mailman to got it proper configured, but in my test it finally worked. At  https://github.com/Shadowghost/mailcow-mailman3-dockerized there is a try to combine both projects. I didn't tested it out yet, working on my own compose. 

For web it is strongly recommended to have a reverse proxy in front of it.

**Comment by strarsis** [comment]
@monofox: Would it be worth the extra costs of a separate server/cloud instance just for the mailer/newsletter/newsgroup daemon? OTOH, mailcodw already ships with extra web services like SOGO.

**Comment by monofox** [comment]
@strarsis In regular cases for small usage not required from my point of view. Mostly depends on the host systems capabilities and resources.

**Comment by strarsis** [comment]
@monofox: There are also other services like mailmonk for newsletters/mailing lists. Any recommendations?

**Comment by g4rf** [comment]
I wrote [a guide](https://github.com/g4rf/dockerized-mailcow-mailman) to install and config [mailcow-dockerized](https://github.com/mailcow/mailcow-dockerized) with [docker-mailman](https://github.com/maxking/docker-mailman). It's now in a kind of beta state, but may help to get it working. Help and bug reports are appreciated.

Repo: [github.com/g4rf/dockerized-mailcow-mailman](https://github.com/g4rf/dockerized-mailcow-mailman)

**Comment by strarsis** [comment]
Not stale!
