### ISSUE TITLE
[BUG] Postgres version still on 9.6 in docker-compose file

### ISSUE THREAD

**Issue by dansou901** [maxking/docker-mailman#404]
**Tag/version of Container Images**
latest
There is no information anywhere to find which postgres versions are supported by Mailman. Is it possible to run Mailman 3 with postgres 12? If yes, please update the compose file accordingly. Thanks!

Regards,
dansou901

**Comment by maxking** [comment]
Yes, it is posisble to run Mailman3 with new versions of Postgres. However, upgrading the docker-compose is tricky because we'd need some manual steps there to upgrade to newer major versions. 

I hate to kick the can down the road further, but since 9.6 is still a supported version, unless there is a real use case to bump to newer versions, I don't want manual ugprade steps right now.
