### ISSUE TITLE
[BUG] Compatibility issue

### ISSUE THREAD

**Issue by danil-smirnov** [maxking/docker-mailman#452]
Hi, [this recent change](https://github.com/maxking/docker-mailman/commit/c10aa6fce479a78a6c51ac41f0f1f0963bd20d0b#diff-27e621da191f9972846a94828429f1f91d0cdde5cb7ff3ddddc5fe8db38797f2R33) caused incompatibility with other orchestration ([Kubernetes](https://github.com/danil-smirnov/mailman-helm-chart)) as `hostname` of a pod is usually not resolvable inside Kubernetes. The previous approach with IP addresses might be far from ideal bit it worked. Could we revert the change, please?

**Comment by maxking** [comment]
Instead of reverting the change, it is probably a better idea to fix forward since the offending commit isn't released yet.

We could add a try-except for the `gethostbyname` call and let it fail when the default hostname isn't resolvable. We could also make that optional by allowing users to pass in the hostname via env variable.

Also, there is a bug with Postorius using the "mailman-web" hostname in the settings.py which slipped by me during the review, that needs fixing too.

**Comment by danil-smirnov** [comment]
Sure I didn't mean reverting the full change - just the line referenced! I'm not sure this line makes any sense. Are you @maxking ?

**Comment by maxking** [comment]
`gethostbyname` will add the IP of the Pod to the `ALLOWED_HOSTS` so that Django is accessible using that IP instead of the hostname in the $HOST part of the request. It does make sense, just that it doesn't apply when the hostname of the container itself isn't "mailman-web" for example when used outside of the provided compose files.

**Comment by danil-smirnov** [comment]
Hey @maxking , you are probably talking about another issue I've filed, not his one.

Here I'm talking about the change from
```
export MM_HOSTNAME=`hostname -i`
```
to
```
export MM_HOSTNAME=`hostname`
```
I'm not sure it make sense to use the hostname here even in case of docker-compose setup.

**Comment by danil-smirnov** [comment]
@maxking This is issue 2 from [this](https://mail.python.org/archives/list/mailman-developers@python.org/message/MZRQLE4EM7SBXDJIMA3QDPQLOAQJ2JW4/).

**Comment by maxking** [comment]
You are right, I think it should be IP address or whatever address Mailman is externally reachable at instead of the hostname of the container. The default if not specified should be 127.0.0.1 I think (what `hostname -i` was getting us previously) and in Kubernetes, you can pass in the Pod's IP address using jsonpath.

**Comment by danil-smirnov** [comment]
Nope, in Kubernetes `hostname -i` is giving the pod's external IP address. e.g.
```
bash-5.0# hostname -i
10.42.0.166
```
which works fine, as well as in docker-compose setup.

This is why I think this change (one line) should be reverted as it obviously breaks things.

**Comment by maxking** [comment]
yep, makes sense. the default localhost works in my compose files, but it obviously breaks in other scenarios. `hostname -i` is a more sane default value. 

I'll close #453 for now, but I don't think i can get to this soon. Do you want to open a PR to revert the change back?

**Comment by danil-smirnov** [comment]
Sure @maxking - https://github.com/maxking/docker-mailman/pull/454
