### ISSUE TITLE
[BUG] docker-compose.yaml not working

### ISSUE THREAD

**Issue by m0wer** [maxking/docker-mailman#461]
Current `docker-compose.yaml` from `master` is not working. Database fails with `LOG:  unexpected EOF on client connection with an open transaction`.

It would be nice to have a minimal working example.

Thanks for the project!

**Comment by szarnyasg** [comment]
Hi @m0wer, did you manage to find a workaround for this issue? I also ran into issues with `docker-compose.yaml` - the database starts for me but getting a password reset fails: #443.
(I turned on Postgres' logging and it didn't have any errors. The web and database containers can connect to each other, the problem seems to be on the django/hyperkitty side.)

**Comment by m0wer** [comment]
> Hi @m0wer, did you manage to find a workaround for this issue? I also ran into issues with `docker-compose.yaml` - the database starts for me but getting a password reset fails: #443.
> (I turned on Postgres' logging and it didn't have any errors. The web and database containers can connect to each other, the problem seems to be on the django/hyperkitty side.)

No, unfortunately. I did the same checks as you did and gave up :(

**Comment by maxking** [comment]
Can you try using 0.3.10 images in your compose and see if you get the same issue?

**Comment by szarnyasg** [comment]
Hi @maxking, I figured out the problem. It was me binding the machine incorrectly. Followup in #464
