### ISSUE TITLE
[REQUEST] Please document how to migrate from Mailman 2.1

### ISSUE THREAD

**Issue by pcolmer** [maxking/docker-mailman#487]
The documentation at https://docs.mailman3.org/en/latest/migration.html specifies the following commands to be run:

```
mailman import21 foo-list@example.com /path/to/mailman2/foo-list/config.pck
python manage.py hyperkitty_import -l foo-list@example.com $var_prefix/archives/private/foo-list.mbox/foo-list.mbox
python manage.py update_index_one_list foo-list@example.com
```

https://github.com/maxking/docker-mailman/issues/445 suggests:

> Try running python manage.py hyperkitty_import --help inside the mailman-web container. It should work.

Presumably `$var_prefix` is simply replaced by the appropriate full path so I can just mount the `$var_prefix` directory into the container for the command to succeed.

However, I'm not clear which container holds the `mailman` command. Is it also the mailman-web container? Again, it looks like a mount needs to be done.

Thank you.

**Comment by maxking** [comment]
There are two command, one for importing the list configs (`mailman import21`) and other for importing the archives (`python manage.py hyperkitty_import`).

You want to run `mailman import21` command inside the `mailman-core` container, which runs Mailman Core engine. You can copy the `config.pck` from your mailman2 into the container using `docker cp` command (https://docs.docker.com/engine/reference/commandline/cp/) or just put the file in `/opt/mailman/core` on the host and it should be available at `/opt/mailman` inside the `mailman core` container because of the existing volume mapping (https://github.com/maxking/docker-mailman/blob/main/docker-compose.yaml#L9).

To import the archives, you want to do the same thing in the `mailman-web` container. Note that the `$var_prefix/...` is jus the suggested path where your archives are in your mailman2 install, you essentially want the mbox file with your archives and make it visible inside the `mailman-web` container by either copying or adding it to `/opt/mailman/web` in your host which will make it available at `/opt/mailman-web-data` in your `mailman-web` container due to this mount (https://github.com/maxking/docker-mailman/blob/main/docker-compose.yaml#L36).
